version: '3.8'

services:
  scoring-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=${BUILD_TYPE:-build:local}  # Default to local build if not specified
    ports:
      - "6173:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8080
    networks:
      - scoring-network

networks:
  scoring-network:
    driver: bridge
