version: '3.8'

services:
  scoring-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TYPE=${BUILD_TYPE:-build:local}  # Default to local build if not specified
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://host.docker.internal:8080  # Use host.docker.internal to access host machine
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Required for Windows Docker Desktop
    networks:
      - default

networks:
  default:
    name: scoring-network
    driver: bridge
